services:
  cowrie:
    image: cowrie/cowrie:sha-cd0770d
    container_name: honeywatch-cowrie
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - cowrie-logs:/cowrie/cowrie-git/var/log/cowrie
      - ./cowrie/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ./cowrie/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro
      - ./cowrie/fs/centos-stream10.pickle:/cowrie/cowrie-git/src/cowrie/data/fs.pickle:ro
      - ./cowrie/cmdoutput.json:/cowrie/cowrie-git/src/cowrie/data/cmdoutput.json:ro
      - ./cowrie/honeyfs:/cowrie/cowrie-git/honeyfs:ro
      - ./cowrie/txtcmds:/cowrie/cowrie-git/src/cowrie/data/txtcmds:ro
    networks:
      - honeywatch

  postgres:
    image: postgres:16-alpine
    container_name: honeywatch-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - honeywatch
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  ingestor:
    build: ./ingestor
    container_name: honeywatch-ingestor
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      # allows localhost sessions to count
      DROP_LOOPBACK: "0"
    volumes:
      - cowrie-logs:/logs:ro
      - ./ingestor/data:/data/geoip:ro
    networks:
      - honeywatch

  api:
    build: ./api
    container_name: honeywatch-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
    networks:
      - honeywatch

  dashboard:
    build: ./dashboard
    container_name: honeywatch-dashboard
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - honeywatch

volumes:
  cowrie-logs:
  postgres-data:

networks:
  honeywatch:
    driver: bridge
