set dotenv-load := true

default:
    @just --list

# ---------------------------------------------------------------------------
# Dev stack
# ---------------------------------------------------------------------------

# Bring up the dev stack.
dev:
    docker compose up -d --build

# Tail logs. `just logs` follows everything; `just logs api ingestor` filters.
logs *services:
    docker compose logs -f {{services}}

# Stop and remove the dev stack.
down:
    docker compose down

# SSH into the local cowrie to generate real events. Type any password when
# prompted; cowrie logs both successful and failed attempts. Default user is
# root; override with `just attack admin`.
attack user="root":
    ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{user}}@localhost || true

# Stream the raw cowrie JSON events -- the exact input the ingestor parses.
cowrie-log:
    docker compose exec ingestor tail -f /logs/cowrie.json

# Fetch GeoLite2-City and GeoLite2-ASN mmdb files into ingestor/data/.
# Requires MAXMIND_ACCOUNT_ID and MAXMIND_LICENSE_KEY in .env
fetch-mmdb:
    ./scripts/fetch-mmdb.sh ingestor/data

# ---------------------------------------------------------------------------
# Database (one postgres container hosts both `${POSTGRES_DB}` for dev and
# `honeywatch_test` for the test suite - transactions roll back per-test)
# ---------------------------------------------------------------------------

# Run alembic migrations against the dev database.
db-upgrade:
    docker compose exec api alembic upgrade head

# Roll back one alembic migration on the dev database.
db-downgrade:
    docker compose exec api alembic downgrade -1

# Show current alembic head(s); should print exactly one.
db-heads:
    docker compose exec api alembic heads

# Generate an autogenerated alembic revision by diffing models vs the live
# dev DB. Usage: `just db-revision "add foo column"`. Review the file before
# committing - autogenerate misses index changes, server defaults, etc.
db-revision message:
    docker compose exec api alembic revision --autogenerate -m "{{message}}"
    @echo "review generated file under api/alembic/versions/ then 'just db-upgrade'"

# Generate an empty alembic revision (for data migrations, CONCURRENTLY, etc).
db-revision-empty message:
    docker compose exec api alembic revision -m "{{message}}"

# Open a psql shell in the live dev database.
db-shell:
    docker compose exec postgres psql -U "$POSTGRES_USER" "$POSTGRES_DB"

# Bring the dev postgres up.
test-db-init:
    docker compose up -d postgres
    @echo "waiting for postgres..."
    @ready=0; \
    for i in $(seq 1 30); do \
      if docker compose exec -T postgres pg_isready -U "$POSTGRES_USER" >/dev/null 2>&1; then \
        ready=1; break; \
      fi; \
      sleep 1; \
    done; \
    if [ "$ready" -ne 1 ]; then \
      echo "postgres not ready after 30s; aborting" >&2; \
      exit 1; \
    fi
    @docker compose exec -T postgres sh -c \
      'psql -U "$POSTGRES_USER" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='"'"'honeywatch_test'"'"'" | grep -q 1 \
       || psql -U "$POSTGRES_USER" -d postgres -c "CREATE DATABASE honeywatch_test OWNER \"$POSTGRES_USER\""'
    @echo "honeywatch_test ready"

# Open a psql shell in the test database.
test-db-shell:
    docker compose exec postgres psql -U "$POSTGRES_USER" honeywatch_test

# Drop the test database.
test-db-reset:
    docker compose exec -T postgres psql -U "$POSTGRES_USER" -d postgres \
      -c "DROP DATABASE IF EXISTS honeywatch_test;"
    @just test-db-init

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

# Iterate fast: pytest only against the dev postgres' test DB.
# Assumes `just dev` (or at least `just test-db-init`) has been run.
test-api:
    cd api && \
      POSTGRES_HOST=localhost \
      POSTGRES_PORT="${POSTGRES_HOST_PORT:-5433}" \
      POSTGRES_TEST_DB=honeywatch_test \
      uv run pytest -q

# Iterate fast: ingestor pytest. Uses the same dev postgres + test DB as the
# api suite; assumes `just dev` (or at least `just test-db-init`) has been run.
test-ingestor:
    cd ingestor && \
      POSTGRES_HOST=localhost \
      POSTGRES_PORT="${POSTGRES_HOST_PORT:-5433}" \
      POSTGRES_TEST_DB=honeywatch_test \
      uv run pytest -q

# Iterate fast: dashboard build (vue-tsc + vite). Mirrors CI.
test-dashboard:
    cd dashboard && pnpm install --frozen-lockfile && pnpm build

# Full CI mirror: ruff + pyright + pytest (api + ingestor) + dashboard
# build/lint/typecheck/unit. Ensures the dev postgres is up and the test DB
# exists. Green here means green in `.github/workflows/ci.yml` -- except the
# Playwright/axe e2e, which CI runs but is omitted here to avoid a browser
# download on every local run (use `just test-dashboard-e2e` for that).
test: test-db-init
    cd api && uv run ruff check .
    cd api && uv run ruff format --check .
    cd api && uv run pyright
    just test-api
    cd ingestor && uv run ruff check .
    cd ingestor && uv run ruff format --check .
    cd ingestor && uv run pyright
    just test-ingestor
    just lint-dashboard
    just typecheck-dashboard
    just test-dashboard
    just test-dashboard-unit

# Full local gate: test suite plus OpenAPI drift check.
check: test openapi-check

# ---------------------------------------------------------------------------
# dashboard
# ---------------------------------------------------------------------------

# Install dashboard deps from the committed lockfile (mirrors CI).
install-dashboard:
    cd dashboard && pnpm install --frozen-lockfile

# Vite dev server on http://localhost:5173. Use when iterating outside the
# docker compose stack; otherwise `just dev` runs the full stack.
dev-dashboard:
    cd dashboard && pnpm dev

# vue-tsc --noEmit. Fast type-only check, no build artifacts.
typecheck-dashboard:
    cd dashboard && pnpm typecheck

# Production build: typecheck + Vite bundle into dashboard/dist/.
build-dashboard:
    cd dashboard && pnpm build

# Vitest unit tests with the coverage gate (mirrors CI).
test-dashboard-unit:
    cd dashboard && pnpm test --coverage

# Playwright e2e suite.
test-dashboard-e2e:
    cd dashboard && pnpm e2e

# ESLint with --max-warnings 0.
lint-dashboard:
    cd dashboard && pnpm lint

# Prettier --write across dashboard/.
format-dashboard:
    cd dashboard && pnpm format

# Prettier --check; CI-friendly, non-mutating.
format-check-dashboard:
    cd dashboard && pnpm format:check

# Regen TS SDK + tanstack-vue-query helpers from api/openapi.json.
openapi-gen:
    cd dashboard && pnpm openapi:gen

# Dump the spec to api/openapi.json.
api-openapi:
    cd api && FLASK_APP=src.app:create_app FLASK_SECRET_KEY=openapi-dump ENVIRONMENT=development uv run flask openapi-dump --output openapi.json

# Full regen: dump backend spec + regen frontend SDK.
openapi-regen: api-openapi openapi-gen

# CI drift gate: regen + fail if the committed spec or generated client drifted.
openapi-check: openapi-regen
    git add -A -- api/openapi.json dashboard/src/api/generated
    git diff --cached --exit-code -- api/openapi.json dashboard/src/api/generated
