apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: honeywatch

resources:
  - namespace.yaml
  - dashboard.yaml
  - egress.yaml
  - middleware.yaml
  - ingress.yaml
  - secret.yaml

images:
  - name: ghcr.io/straightchlorine/honeywatch/dashboard
    newTag: 0.1.1
