// No raw non-ASCII in source. Symbols must be HTML entities or inline SVG
// so they render consistently instead of tofu/mismatched glyphs.
// Plain node script, not a `grep -P` one-liner - unreliable in some sandboxes.
import { readFileSync, globSync } from 'node:fs' // fs.globSync: node >= 22

let bad = false
for (const f of globSync('src/**/*.{vue,ts,css}')) {
  if (f.startsWith('src/api/generated/')) continue // vendored, regenerated by openapi:gen
  // eslint-disable-next-line no-control-regex -- deliberately includes the C0/DEL range
  const m = readFileSync(f, 'utf8').match(/[^\x00-\x7f]/)
  if (m) {
    console.error(`${f}: non-ASCII character ${JSON.stringify(m[0])}`)
    bad = true
  }
}
process.exit(bad ? 1 : 0)
